package org.eumetsat.usd.gcp.client.gin;

import org.eumetsat.usd.gcp.client.presenter.PlotPresenter;
import org.eumetsat.usd.gcp.client.presenter.StaticPlotPresenter;

import com.google.gwt.inject.client.AsyncProvider;
import com.google.gwt.inject.client.GinModules;
import com.google.gwt.inject.client.Ginjector;
import com.google.web.bindery.event.shared.EventBus;
import com.gwtplatform.dispatch.rpc.client.gin.RpcDispatchAsyncModule;
import com.gwtplatform.mvp.client.proxy.PlaceManager;

/**
 * Client GIN Injector. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
@GinModules({ RpcDispatchAsyncModule.class, ClientModule.class })
public interface ClientGinjector extends Ginjector
{
    /**
     * Get Event Bus.
     * 
     * @return event bus.
     */
    EventBus getEventBus();

    /**
     * Get Place Manager.
     * 
     * @return place manager.
     */
    PlaceManager getPlaceManager();

    /**
     * Get Plot Presenter.
     * 
     * @return plot presenter.
     */
    AsyncProvider<PlotPresenter> getPlotPresenter();

    /**
     * Get Static Plot Presenter.
     * 
     * @return static plot presenter.
     */
    AsyncProvider<StaticPlotPresenter> getStaticPlotPresenter();
}
