package org.eumetsat.usd.gcp.client.gin;

import org.eumetsat.usd.gcp.client.place.ClientPlaceManager;
import org.eumetsat.usd.gcp.client.place.DefaultPlace;
import org.eumetsat.usd.gcp.client.place.NameTokens;
import org.eumetsat.usd.gcp.client.presenter.ConfirmationPresenter;
import org.eumetsat.usd.gcp.client.presenter.ErrorPresenter;
import org.eumetsat.usd.gcp.client.presenter.ExportedImagePresenter;
import org.eumetsat.usd.gcp.client.presenter.LoadingPresenter;
import org.eumetsat.usd.gcp.client.presenter.LoginPresenter;
import org.eumetsat.usd.gcp.client.presenter.MessagePresenter;
import org.eumetsat.usd.gcp.client.presenter.PlotPresenter;
import org.eumetsat.usd.gcp.client.presenter.RegisterPresenter;
import org.eumetsat.usd.gcp.client.presenter.StaticPlotPresenter;
import org.eumetsat.usd.gcp.client.presenter.UserGuidePresenter;
import org.eumetsat.usd.gcp.client.view.ConfirmationView;
import org.eumetsat.usd.gcp.client.view.ErrorView;
import org.eumetsat.usd.gcp.client.view.ExportedImageView;
import org.eumetsat.usd.gcp.client.view.LoadingView;
import org.eumetsat.usd.gcp.client.view.LoginView;
import org.eumetsat.usd.gcp.client.view.MessageView;
import org.eumetsat.usd.gcp.client.view.PlotView;
import org.eumetsat.usd.gcp.client.view.RegisterView;
import org.eumetsat.usd.gcp.client.view.StaticPlotView;
import org.eumetsat.usd.gcp.client.view.UserGuideView;

import com.google.web.bindery.event.shared.EventBus;
import com.gwtplatform.mvp.client.gin.AbstractPresenterModule;
import com.gwtplatform.mvp.client.gin.DefaultModule;

/**
 * Client Module. Generated by GWTP Plugin.
 */
public class ClientModule extends AbstractPresenterModule
{

    @Override
    protected final void configure()
    {
        install(new DefaultModule.Builder().placeManager(ClientPlaceManager.class).build());

        requestStaticInjection(EventBus.class);

        bindPresenter(PlotPresenter.class, PlotPresenter.MyView.class, PlotView.class, PlotPresenter.MyProxy.class);

        bindConstant().annotatedWith(DefaultPlace.class).to(NameTokens.MAIN);

        bindPresenterWidget(MessagePresenter.class, MessagePresenter.MyView.class, MessageView.class);

        bindPresenterWidget(ErrorPresenter.class, ErrorPresenter.MyView.class, ErrorView.class);

        bindPresenterWidget(ExportedImagePresenter.class, ExportedImagePresenter.MyView.class, ExportedImageView.class);

        bindPresenterWidget(ConfirmationPresenter.class, ConfirmationPresenter.MyView.class, ConfirmationView.class);

        bindPresenter(StaticPlotPresenter.class, StaticPlotPresenter.MyView.class, StaticPlotView.class,
                StaticPlotPresenter.MyProxy.class);

        bindPresenterWidget(LoginPresenter.class, LoginPresenter.MyView.class, LoginView.class);

        bindPresenterWidget(RegisterPresenter.class, RegisterPresenter.MyView.class, RegisterView.class);

        bindPresenterWidget(LoadingPresenter.class, LoadingPresenter.MyView.class, LoadingView.class);

        bindPresenterWidget(UserGuidePresenter.class, UserGuidePresenter.MyView.class, UserGuideView.class);
    }
}
