package org.eumetsat.usd.gcp.server.persistence;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlotConfiguration generated by hbm2java.
 */
@Entity
@Table(name = "plot_configuration")
public class PlotConfiguration implements java.io.Serializable
{
    // ------------------------------
    // Database column names
    // ------------------------------
    /** Plot Configuration Id Column Name. */
    public static final String ID = "plot_configuration_id";
    /** Name Column Name. */
    public static final String NAME = "name";
    /** Server Column Name. */
    public static final String SERVER = "server";
    /** Source Column Name. */
    public static final String GPRC = "source";
    /** Type Column Name. */
    public static final String CORRTYPE = "type";
    /** Sat/instr. Column Name. */
    public static final String SAT_INSTR = "sat_instr";
    /** Reference sat/instr. Column Name. */
    public static final String REF_SAT_INSTR = "ref_sat_instr";
    /** Mode Column Name. */
    public static final String MODE = "mode";
    /** Year Column Name. */
    public static final String YEAR = "year";
    /** Date Column Name. */
    public static final String DATETIME = "date";
    /** Version Column Name. */
    public static final String VERSION = "version";
    /** Channel Column Name. */
    public static final String CHANNEL = "channel";
    /** Scene Tb Column Name. */
    public static final String SCENE_TB = "scene_tb";

    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -288612437644193990L;

    /** Unique Id. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = ID)
    private long id;

    /** Name Column. */
    @Column(name = NAME, nullable = false, length = 255)
    private String name;

    /** Server Column. */
    @Column(name = SERVER, length = 100)
    private String server;

    /** Source Column. */
    @Column(name = GPRC, length = 100)
    private String gprc;

    /** Type Column. */
    @Column(name = CORRTYPE, length = 100)
    private String corrType;

    /** Sat/instr. Column. */
    @Column(name = SAT_INSTR, length = 100)
    private String satInstr;

    /** Reference sat/instr. Column. */
    @Column(name = REF_SAT_INSTR, length = 100)
    private String refSatInstr;

    /** Mode Column. */
    @Column(name = MODE, length = 100)
    private String mode;

    /** Year Column. */
    @Column(name = YEAR, length = 10)
    private String year;

    /** Date Column. */
    @Column(name = DATETIME, length = 20)
    private String dateTime;

    /** Version Column. */
    @Column(name = VERSION, length = 10)
    private String version;

    /** Channel Column. */
    @Column(name = CHANNEL, length = 10)
    private String channel;

    /** Scene Tb Column. */
    @Column(name = SCENE_TB, precision = 22, scale = 0)
    private Double sceneTb;

    /** User Column. */
    @ManyToOne
    @JoinColumn(name = User.ID, insertable = false, updatable = false, nullable = false)
    private User user;

    /**
     * Constructor.
     */
    public PlotConfiguration()
    {
    }

    /**
     * Constructor.
     * 
     * @param name
     *            name.
     */
    public PlotConfiguration(final String name)
    {
        this.name = name;
    }

    /**
     * Constructor.
     * 
     * @param name
     *            name.
     * @param server
     *            server.
     * @param gprc
     *            GPRC.
     * @param corrType
     *            corrType.
     * @param satInstr
     *            sat/instr.
     * @param refSatInstr
     *            reference sat/instr.
     * @param mode
     *            mode.
     * @param year
     *            year.
     * @param dateTime
     *            dateTime.
     * @param version
     *            version.
     * @param channel
     *            channel.
     * @param sceneTb
     *            scene Tb.
     */
    public PlotConfiguration(final String name, final String server, final String gprc, final String corrType,
            final String satInstr, final String refSatInstr, final String mode, final String year, final String dateTime,
            final String version, final String channel, final Double sceneTb)
    {
        this.name = name;
        this.server = server;
        this.gprc = gprc;
        this.corrType = corrType;
        this.satInstr = satInstr;
        this.refSatInstr = refSatInstr;
        this.mode = mode;
        this.year = year;
        this.dateTime = dateTime;
        this.version = version;
        this.channel = channel;
        this.sceneTb = sceneTb;
    }

    /**
     * Get Id.
     * 
     * @return id.
     */
    public final long getId()
    {
        return this.id;
    }

    /**
     * Set id.
     * 
     * @param id
     *            id.
     */
    public final void setId(final long id)
    {
        this.id = id;
    }

    /**
     * Get version.
     * 
     * @return version.
     */
    public final String getVersion()
    {
        return this.version;
    }

    /**
     * Set version.
     * 
     * @param version
     *            version.
     */
    public final void setVersion(final String version)
    {
        this.version = version;
    }

    /**
     * Get user.
     * 
     * @return user.
     */
    public final User getUser()
    {
        return this.user;
    }

    /**
     * Set user.
     * 
     * @param user
     *            user.
     */
    public final void setUser(final User user)
    {
        this.user = user;
    }

    /**
     * Get name.
     * 
     * @return name.
     */
    public final String getName()
    {
        return this.name;
    }

    /**
     * Set name.
     * 
     * @param name
     *            name.
     */
    public final void setName(final String name)
    {
        this.name = name;
    }

    /**
     * Get server.
     * 
     * @return server.
     */
    public final String getServer()
    {
        return this.server;
    }

    /**
     * Set server.
     * 
     * @param server
     *            server.
     */
    public final void setServer(final String server)
    {
        this.server = server;
    }

    /**
     * Get GPRC.
     * 
     * @return gprc.
     */
    public final String getGPRC()
    {
        return this.gprc;
    }

    /**
     * Set GPRC.
     * 
     * @param gprc
     *            GPRC.
     */
    public final void setGPRC(final String gprc)
    {
        this.gprc = gprc;
    }

    /**
     * Get correction type.
     * 
     * @return corrType.
     */
    public final String getCorrType()
    {
        return this.corrType;
    }

    /**
     * Set correction type.
     * 
     * @param corrType
     *            correction type.
     */
    public final void setCorrType(final String corrType)
    {
        this.corrType = corrType;
    }

    /**
     * Get sat/instr.
     * 
     * @return sat/instr.
     */
    public final String getSatInstr()
    {
        return this.satInstr;
    }

    /**
     * Set sat/instr.
     * 
     * @param satInstr
     *            sat/instr.
     */
    public final void setSatInstr(final String satInstr)
    {
        this.satInstr = satInstr;
    }

    /**
     * Get reference sat/instr.
     * 
     * @return reference sat/instr.
     */
    public final String getRefSatInstr()
    {
        return this.refSatInstr;
    }

    /**
     * Set reference sat/instr.
     * 
     * @param refSatInstr
     *            reference sat/instr.
     */
    public final void setRefSatInstr(final String refSatInstr)
    {
        this.refSatInstr = refSatInstr;
    }

    /**
     * Get mode.
     * 
     * @return mode.
     */
    public final String getMode()
    {
        return this.mode;
    }

    /**
     * Set mode.
     * 
     * @param mode
     *            mode.
     */
    public final void setMode(final String mode)
    {
        this.mode = mode;
    }

    /**
     * Get year.
     * 
     * @return year.
     */
    public final String getYear()
    {
        return this.year;
    }

    /**
     * Set year.
     * 
     * @param year
     *            year.
     */
    public final void setYear(final String year)
    {
        this.year = year;
    }

    /**
     * Get date-time.
     * 
     * @return dateTime.
     */
    public final String getDateTime()
    {
        return this.dateTime;
    }

    /**
     * Set date-time.
     * 
     * @param dateTime
     *            date-time.
     */
    public final void setDate(final String dateTime)
    {
        this.dateTime = dateTime;
    }

    /**
     * Get channel.
     * 
     * @return channel.
     */
    public final String getChannel()
    {
        return this.channel;
    }

    /**
     * Set channel.
     * 
     * @param channel
     *            channel.
     */
    public final void setChannel(final String channel)
    {
        this.channel = channel;
    }

    /**
     * Get scene Tb.
     * 
     * @return scene Tb.
     */
    public final Double getSceneTb()
    {
        return this.sceneTb;
    }

    /**
     * Set scene Tb.
     * 
     * @param sceneTb
     *            scene Tb.
     */
    public final void setSceneTb(final Double sceneTb)
    {
        this.sceneTb = sceneTb;
    }

}
