package org.eumetsat.usd.gcp.client.place;

import com.google.gwt.place.shared.PlaceHistoryHandler.Historian;
import com.google.inject.Inject;
import com.google.web.bindery.event.shared.EventBus;
import com.gwtplatform.mvp.client.proxy.PlaceManagerImpl;
import com.gwtplatform.mvp.shared.proxy.PlaceRequest;
import com.gwtplatform.mvp.shared.proxy.TokenFormatter;

/**
 * Client Place Manager. Generated by GWTP Plugin.
 * 
 * @author USC/C/PBe
 */
public class ClientPlaceManager extends PlaceManagerImpl
{
    /** Default Place Request. */
    private final PlaceRequest defaultPlaceRequest;

    /**
     * Constructor.
     * 
     * @param eventBus
     *            event bus.
     * @param tokenFormatter
     *            token formatter.
     * @param defaultPlaceNameToken
     *            default place name token.
     */
    @Inject
    public ClientPlaceManager(final EventBus eventBus, final TokenFormatter tokenFormatter, Historian historian,
            @DefaultPlace final String defaultPlaceNameToken)
    {
        super(eventBus, tokenFormatter, historian);
        this.defaultPlaceRequest = new PlaceRequest.Builder().nameToken(defaultPlaceNameToken).build();
    }

    @Override
    public final void revealDefaultPlace()
    {
        revealPlace(defaultPlaceRequest, false);
    }
}
