package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.persistence.PersistenceManager;
import org.eumetsat.usd.gcp.shared.action.ClearSavedPlotConfigs;
import org.eumetsat.usd.gcp.shared.action.ClearSavedPlotConfigsResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Clear Saved Plot Configurations Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class ClearSavedPlotConfigsActionHandler implements
        ActionHandler<ClearSavedPlotConfigs, ClearSavedPlotConfigsResult>
{
    /** Persistence Manager. */
    private PersistenceManager persistenceManager;

    /**
     * Constructor.
     */
    @Inject
    public ClearSavedPlotConfigsActionHandler(final PersistenceManager persistenceManager)
    {
        this.persistenceManager = persistenceManager;
    }

    @Override
    public final ClearSavedPlotConfigsResult execute(final ClearSavedPlotConfigs action, final ExecutionContext context)
            throws ActionException
    {
        persistenceManager.clearPlotConfigsForUser(action.getUserID());

        return new ClearSavedPlotConfigsResult();
    }

    @Override
    public final void undo(final ClearSavedPlotConfigs action, final ClearSavedPlotConfigsResult result,
            final ExecutionContext context) throws ActionException
    {
    }

    @Override
    public final Class<ClearSavedPlotConfigs> getActionType()
    {
        return ClearSavedPlotConfigs.class;
    }
}
