package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.data.CalibrationDataManager;
import org.eumetsat.usd.gcp.shared.action.ClearData;
import org.eumetsat.usd.gcp.shared.action.ClearDataResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Clear Data Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class ClearDataActionHandler implements ActionHandler<ClearData, ClearDataResult>
{
    /** Calibration Data Manager. */
    private final CalibrationDataManager calibrationDataManager;

    /**
     * Constructor.
     * 
     * @param calibrationDataManager
     *            calibration data manager.
     */
    @Inject
    public ClearDataActionHandler(final CalibrationDataManager calibrationDataManager)
    {
        this.calibrationDataManager = calibrationDataManager;
    }

    @Override
    public final ClearDataResult execute(final ClearData action, final ExecutionContext context) throws ActionException
    {
        calibrationDataManager.clearDataForUser(action.getUserID());

        return new ClearDataResult();
    }

    @Override
    public final void undo(final ClearData action, final ClearDataResult result, final ExecutionContext context)
            throws ActionException
    {
    }

    @Override
    public final Class<ClearData> getActionType()
    {
        return ClearData.class;
    }
}
