package org.eumetsat.usd.gcp.server.action;

import java.util.UUID;

import org.eumetsat.usd.gcp.shared.action.GenerateClientID;
import org.eumetsat.usd.gcp.shared.action.GenerateClientIDResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Generate User ID Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GenerateUserIDActionHandler implements ActionHandler<GenerateClientID, GenerateClientIDResult>
{
    /**
     * Constructor.
     */
    @Inject
    public GenerateUserIDActionHandler()
    {
    }

    @Override
    public final GenerateClientIDResult execute(final GenerateClientID action, final ExecutionContext context)
            throws ActionException
    {
        GenerateClientIDResult result = new GenerateClientIDResult(UUID.randomUUID().toString());

        return result;
    }

    @Override
    public final void undo(final GenerateClientID action, final GenerateClientIDResult result,
            final ExecutionContext context) throws ActionException
    {
    }

    @Override
    public final Class<GenerateClientID> getActionType()
    {
        return GenerateClientID.class;
    }
}
