package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.data.CalibrationDataManager;
import org.eumetsat.usd.gcp.shared.action.GetDatasetsNames;
import org.eumetsat.usd.gcp.shared.action.GetDatasetsNamesResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Datasets Names Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetDatasetsNamesActionHandler implements ActionHandler<GetDatasetsNames, GetDatasetsNamesResult>
{
    /** Calibration Data Manager. */
    private final CalibrationDataManager calibrationDataManager;

    /**
     * Constructor.
     */
    @Inject
    public GetDatasetsNamesActionHandler(final CalibrationDataManager calibrationDataManager)
    {
        this.calibrationDataManager = calibrationDataManager;
    }

    @Override
    public final GetDatasetsNamesResult execute(final GetDatasetsNames action, final ExecutionContext context)
            throws ActionException
    {
        return new GetDatasetsNamesResult(calibrationDataManager.addedSourcesForUser(action.getUserID()));
    }

    @Override
    public final void undo(final GetDatasetsNames action, final GetDatasetsNamesResult result,
            final ExecutionContext context) throws ActionException
    {
    }

    @Override
    public final Class<GetDatasetsNames> getActionType()
    {
        return GetDatasetsNames.class;
    }
}
