package org.eumetsat.usd.gcp.server.action;

import java.util.Collections;
import java.util.List;

import org.eumetsat.usd.gcp.server.catalog.CatalogNavigator;
import org.eumetsat.usd.gcp.server.guice.CatalogNavigatorFactory;
import org.eumetsat.usd.gcp.shared.action.GetDateTimes;
import org.eumetsat.usd.gcp.shared.action.GetDateTimesResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Dates Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetDateTimesActionHandler implements ActionHandler<GetDateTimes, GetDateTimesResult>
{
    /** Catalog Navigator Factory. */
    private CatalogNavigatorFactory catalogNavigatorFactory;

    /**
     * Constructor.
     */
    @Inject
    public GetDateTimesActionHandler(final CatalogNavigatorFactory catalogNavigatorFactory)
    {
        this.catalogNavigatorFactory = catalogNavigatorFactory;
    }

    @Override
    public final GetDateTimesResult execute(final GetDateTimes action, final ExecutionContext context)
            throws ActionException
    {
        CatalogNavigator catalogNavigator = catalogNavigatorFactory.create(action.getCatalog());
        
        List<String> dateTimes = catalogNavigator.getDateTimes(action.getGPRC(),
                action.getCorrType(), action.getSatInstr(), action.getRefSatInstr(), action.getMode(), action.getYear());
        
        Collections.sort(dateTimes);

        return new GetDateTimesResult(dateTimes);
    }

    @Override
    public final void undo(final GetDateTimes action, final GetDateTimesResult result, final ExecutionContext context)
            throws ActionException
    {
    }

    @Override
    public final Class<GetDateTimes> getActionType()
    {
        return GetDateTimes.class;
    }
}
