package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.catalog.CatalogNavigator;
import org.eumetsat.usd.gcp.server.guice.CatalogNavigatorFactory;
import org.eumetsat.usd.gcp.shared.action.GetGPRCs;
import org.eumetsat.usd.gcp.shared.action.GetGPRCsResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Sources Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetGPRCsActionHandler implements ActionHandler<GetGPRCs, GetGPRCsResult>
{
    /** Catalog Navigator Factory. */
    private CatalogNavigatorFactory catalogNavigatorFactory;
    
    /**
     * Constructor.
     */
    @Inject
    public GetGPRCsActionHandler(final CatalogNavigatorFactory catalogNavigatorFactory)
    {
        this.catalogNavigatorFactory = catalogNavigatorFactory;
    }

    @Override
    public final GetGPRCsResult execute(final GetGPRCs action, final ExecutionContext context)
            throws ActionException
    {
        CatalogNavigator catalogNavigator = catalogNavigatorFactory.create(action.getCatalog());

        GetGPRCsResult result = new GetGPRCsResult(catalogNavigator.getGPRCs());

        return result;
    }

    @Override
    public final void undo(final GetGPRCs action, final GetGPRCsResult result, final ExecutionContext context)
            throws ActionException
    {
    }

    @Override
    public final Class<GetGPRCs> getActionType()
    {
        return GetGPRCs.class;
    }
}
