package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.conf.ConfigManager;
import org.eumetsat.usd.gcp.shared.action.GetHelpItems;
import org.eumetsat.usd.gcp.shared.action.GetHelpItemsResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Help Items Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetHelpItemsActionHandler implements ActionHandler<GetHelpItems, GetHelpItemsResult>
{
    /** Configuration Manager. */
    private ConfigManager configManager;

    /**
     * Constructor.
     * 
     * @param configManager
     *            configuration manager.
     */
    @Inject
    public GetHelpItemsActionHandler(final ConfigManager configManager)
    {
        this.configManager = configManager;
    }

    @Override
    public GetHelpItemsResult execute(GetHelpItems action, ExecutionContext context) throws ActionException
    {
        return new GetHelpItemsResult(configManager.getHelpItems());
    }

    @Override
    public void undo(GetHelpItems action, GetHelpItemsResult result, ExecutionContext context) throws ActionException
    {
    }

    @Override
    public Class<GetHelpItems> getActionType()
    {
        return GetHelpItems.class;
    }
}
