package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.conf.ConfigManager;
import org.eumetsat.usd.gcp.shared.action.GetImplementedCatalogs;
import org.eumetsat.usd.gcp.shared.action.GetImplementedCatalogsResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Implemented Catalogs Action Handler. Generated by GWTP Plugin.
 * 
 * @author USC/C/PBe
 */
public class GetImplementedCatalogsActionHandler implements
        ActionHandler<GetImplementedCatalogs, GetImplementedCatalogsResult>
{
    /** Configuration manager. */
    private ConfigManager configManager;

    /**
     * Constructor.
     * 
     * @param configManager
     *            configuration manager.
     */
    @Inject
    public GetImplementedCatalogsActionHandler(final ConfigManager configManager)
    {
        this.configManager = configManager;
    }

    @Override
    public final GetImplementedCatalogsResult execute(final GetImplementedCatalogs action,
            final ExecutionContext context) throws ActionException
    {
        return new GetImplementedCatalogsResult(configManager.getConfiguredCatalogs());
    }

    @Override
    public final void undo(final GetImplementedCatalogs action, final GetImplementedCatalogsResult result,
            final ExecutionContext context) throws ActionException
    {
    }

    @Override
    public final Class<GetImplementedCatalogs> getActionType()
    {
        return GetImplementedCatalogs.class;
    }
}
