package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.catalog.CatalogNavigator;
import org.eumetsat.usd.gcp.server.guice.CatalogNavigatorFactory;
import org.eumetsat.usd.gcp.shared.action.GetModes;
import org.eumetsat.usd.gcp.shared.action.GetModesResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Modes Action Handler. Generated by GWTP Plugin.
 * 
 * @author USC/C/PBe
 */
public class GetModesActionHandler implements ActionHandler<GetModes, GetModesResult>
{
    /** Catalog Navigator Factory. */
    private CatalogNavigatorFactory catalogNavigatorFactory;
    
    /**
     * Constructor.
     */
    @Inject
    public GetModesActionHandler(final CatalogNavigatorFactory catalogNavigatorFactory)
    {
        this.catalogNavigatorFactory = catalogNavigatorFactory;
    }

    @Override
    public final GetModesResult execute(final GetModes action, final ExecutionContext context) throws ActionException
    {
        CatalogNavigator catalogNavigator = catalogNavigatorFactory.create(action.getCatalog());

        GetModesResult result = new GetModesResult(catalogNavigator.getModes(action.getGPRC(), action.getCorrType(),
                action.getSatInstr(), action.getRefSatInstr()));

        return result;
    }

    @Override
    public final void undo(final GetModes action, final GetModesResult result, final ExecutionContext context)
            throws ActionException
    {
    }

    @Override
    public final Class<GetModes> getActionType()
    {
        return GetModes.class;
    }
}
