package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.catalog.CatalogNavigator;
import org.eumetsat.usd.gcp.server.guice.CatalogNavigatorFactory;
import org.eumetsat.usd.gcp.shared.action.GetRefSatInstrs;
import org.eumetsat.usd.gcp.shared.action.GetRefSatInstrsResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Reference Sat/Instrs. Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetRefSatInstrsActionHandler implements ActionHandler<GetRefSatInstrs, GetRefSatInstrsResult>
{
    /** Catalog Navigator Factory. */
    private CatalogNavigatorFactory catalogNavigatorFactory;
    
    /**
     * Constructor.
     */
    @Inject
    public GetRefSatInstrsActionHandler(final CatalogNavigatorFactory catalogNavigatorFactory)
    {
        this.catalogNavigatorFactory = catalogNavigatorFactory;
    }

    @Override
    public final GetRefSatInstrsResult execute(final GetRefSatInstrs action, final ExecutionContext context)
            throws ActionException
    {
        CatalogNavigator catalogNavigator = catalogNavigatorFactory.create(action.getCatalog());

        GetRefSatInstrsResult result =
                new GetRefSatInstrsResult(catalogNavigator.getRefSatInstrs(action.getGPRC(),
                        action.getCorrType(),
                        action.getSatInstr()));

        return result;
    }

    @Override
    public final void undo(final GetRefSatInstrs action, final GetRefSatInstrsResult result,
            final ExecutionContext context) throws ActionException
    {
    }

    @Override
    public final Class<GetRefSatInstrs> getActionType()
    {
        return GetRefSatInstrs.class;
    }
}
