package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.catalog.CatalogNavigator;
import org.eumetsat.usd.gcp.server.guice.CatalogNavigatorFactory;
import org.eumetsat.usd.gcp.shared.action.GetSatInstrs;
import org.eumetsat.usd.gcp.shared.action.GetSatInstrsResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Sat/Instrs. Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetSatInstrsActionHandler implements ActionHandler<GetSatInstrs, GetSatInstrsResult>
{
    /** Catalog Navigator Factory. */
    private CatalogNavigatorFactory catalogNavigatorFactory;
    
    /**
     * Constructor.
     */
    @Inject
    public GetSatInstrsActionHandler(final CatalogNavigatorFactory catalogNavigatorFactory)
    {
        this.catalogNavigatorFactory = catalogNavigatorFactory;
    }

    @Override
    public final GetSatInstrsResult execute(final GetSatInstrs action, final ExecutionContext context)
            throws ActionException
    {
        CatalogNavigator catalogNavigator = catalogNavigatorFactory.create(action.getCatalog());

        GetSatInstrsResult result =
                new GetSatInstrsResult(catalogNavigator.getSatInstrs(action.getGPRC(), action.getCorrType()));

        return result;
    }

    @Override
    public final void undo(final GetSatInstrs action, final GetSatInstrsResult result, final ExecutionContext context)
            throws ActionException
    {
    }

    @Override
    public final Class<GetSatInstrs> getActionType()
    {
        return GetSatInstrs.class;
    }
}
