package org.eumetsat.usd.gcp.server.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.eumetsat.usd.gcp.shared.action.GetUserLoggedIn;
import org.eumetsat.usd.gcp.shared.action.GetUserLoggedInResult;

import com.google.inject.Inject;
import com.google.inject.Provider;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get User Logged In Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetUserLoggedInActionHandler implements ActionHandler<GetUserLoggedIn, GetUserLoggedInResult>
{
    /** Request Provider. */
    private Provider<HttpServletRequest> requestProvider;

    /**
     * Constructor.
     * 
     * @param requestProvider
     *            Request Provider.
     */
    @Inject
    public GetUserLoggedInActionHandler(final Provider<HttpServletRequest> requestProvider)
    {
        this.requestProvider = requestProvider;
    }

    @Override
    public final GetUserLoggedInResult execute(final GetUserLoggedIn action, final ExecutionContext context)
            throws ActionException
    {
        HttpSession session = requestProvider.get().getSession();

        return new GetUserLoggedInResult((String) session.getAttribute("login.authenticated"));
    }

    @Override
    public final void undo(final GetUserLoggedIn action, final GetUserLoggedInResult result,
            final ExecutionContext context) throws ActionException
    {
    }

    @Override
    public final Class<GetUserLoggedIn> getActionType()
    {
        return GetUserLoggedIn.class;
    }
}
