package org.eumetsat.usd.gcp.server.action;

import java.util.Collections;
import java.util.List;

import org.eumetsat.usd.gcp.server.catalog.CatalogNavigator;
import org.eumetsat.usd.gcp.server.guice.CatalogNavigatorFactory;
import org.eumetsat.usd.gcp.shared.action.GetVersions;
import org.eumetsat.usd.gcp.shared.action.GetVersionsResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Versions Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetVersionsActionHandler implements ActionHandler<GetVersions, GetVersionsResult>
{
    /** Catalog Navigator Factory. */
    private CatalogNavigatorFactory catalogNavigatorFactory;
    
    /**
     * Constructor.
     */
    @Inject
    public GetVersionsActionHandler(final CatalogNavigatorFactory catalogNavigatorFactory)
    {
        this.catalogNavigatorFactory = catalogNavigatorFactory;
    }

    @Override
    public final GetVersionsResult execute(final GetVersions action, final ExecutionContext context)
            throws ActionException
    {
        CatalogNavigator catalogNavigator = catalogNavigatorFactory.create(action.getCatalog());

        List<String> versions = catalogNavigator.getVersions(action.getGPRC(),
                action.getCorrType(),
                action.getSatInstr(),
                action.getRefSatInstr(),
                action.getMode(),
                action.getYear(),
                action.getDate());
        
        Collections.sort(versions);
        
        return new GetVersionsResult(versions);
    }

    @Override
    public final void undo(final GetVersions action, final GetVersionsResult result, final ExecutionContext context)
            throws ActionException
    {
    }

    @Override
    public final Class<GetVersions> getActionType()
    {
        return GetVersions.class;
    }
}
