package org.eumetsat.usd.gcp.server.action;

import java.util.Collections;
import java.util.List;

import org.eumetsat.usd.gcp.server.catalog.CatalogNavigator;
import org.eumetsat.usd.gcp.server.guice.CatalogNavigatorFactory;
import org.eumetsat.usd.gcp.shared.action.GetYears;
import org.eumetsat.usd.gcp.shared.action.GetYearsResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Get Years Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetYearsActionHandler implements ActionHandler<GetYears, GetYearsResult>
{
    /** Catalog Navigator Factory. */
    private CatalogNavigatorFactory catalogNavigatorFactory;

    /**
     * Constructor.
     * 
     * @param catalogNavigatorFactory
     *            catalog navigator factory.
     */
    @Inject
    public GetYearsActionHandler(final CatalogNavigatorFactory catalogNavigatorFactory)
    {
        this.catalogNavigatorFactory = catalogNavigatorFactory;
    }

    @Override
    public final GetYearsResult execute(final GetYears action, final ExecutionContext context) throws ActionException
    {
        CatalogNavigator catalogNavigator = catalogNavigatorFactory.create(action.getCatalog());

        List<String> years = catalogNavigator.getYears(action.getGPRC(), action.getCorrType(), action.getSatInstr(),
                action.getRefSatInstr(), action.getMode());

        Collections.sort(years);

        return new GetYearsResult(years);
    }

    @Override
    public final void undo(final GetYears action, final GetYearsResult result, final ExecutionContext context)
            throws ActionException
    {
    }

    @Override
    public final Class<GetYears> getActionType()
    {
        return GetYears.class;
    }
}
