package org.eumetsat.usd.gcp.server.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.eumetsat.usd.gcp.server.persistence.PersistenceManager;
import org.eumetsat.usd.gcp.shared.action.Login;
import org.eumetsat.usd.gcp.shared.action.LoginResult;

import com.google.inject.Inject;
import com.google.inject.Provider;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Login Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class LoginActionHandler implements ActionHandler<Login, LoginResult>
{
    /** Request provider. */
    private final Provider<HttpServletRequest> requestProvider;

    /** Persistence Manager. */
    private PersistenceManager persistenceManager;

    /**
     * Constructor.
     * 
     * @param requestProvider
     *            Request provider.
     */
    @Inject
    public LoginActionHandler(final Provider<HttpServletRequest> requestProvider,
            final PersistenceManager persistenceManager)
    {
        this.persistenceManager = persistenceManager;
        this.requestProvider = requestProvider;
    }

    @Override
    public final LoginResult execute(final Login action, final ExecutionContext context) throws ActionException
    {
        if (persistenceManager.userPasswordIsValid(action.getUsername(), action.getPassword()))
        {
            HttpSession session = requestProvider.get().getSession();
            session.setAttribute("login.authenticated", action.getUsername());

            return new LoginResult(true);

        } else
        {
            return new LoginResult(false);
        }
    }

    @Override
    public final void undo(final Login action, final LoginResult result, final ExecutionContext context)
            throws ActionException
    {
    }

    @Override
    public final Class<Login> getActionType()
    {
        return Login.class;
    }
}
