package org.eumetsat.usd.gcp.server.action;

import org.eumetsat.usd.gcp.server.persistence.PersistenceManager;
import org.eumetsat.usd.gcp.shared.action.RemoveSavedPlotConfig;
import org.eumetsat.usd.gcp.shared.action.RemoveSavedPlotConfigResult;

import com.google.inject.Inject;
import com.gwtplatform.dispatch.rpc.server.ExecutionContext;
import com.gwtplatform.dispatch.rpc.server.actionhandler.ActionHandler;
import com.gwtplatform.dispatch.shared.ActionException;

/**
 * Remove Saved Plot Config Action Handler. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class RemoveSavedPlotConfigActionHandler implements
        ActionHandler<RemoveSavedPlotConfig, RemoveSavedPlotConfigResult>
{
    /** Persistence Manager. */
    private PersistenceManager persistenceManager;

    /**
     * Constructor.
     */
    @Inject
    public RemoveSavedPlotConfigActionHandler(final PersistenceManager persistenceManager)
    {
        this.persistenceManager = persistenceManager;
    }

    @Override
    public final RemoveSavedPlotConfigResult execute(final RemoveSavedPlotConfig action, final ExecutionContext context)
            throws ActionException
    {
        persistenceManager.removePlotConfigForUser(action.getUserID(), action.getPlotConfigName());

        return new RemoveSavedPlotConfigResult();
    }

    @Override
    public final void undo(final RemoveSavedPlotConfig action, final RemoveSavedPlotConfigResult result,
            final ExecutionContext context) throws ActionException
    {
    }

    @Override
    public final Class<RemoveSavedPlotConfig> getActionType()
    {
        return RemoveSavedPlotConfig.class;
    }
}
