package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Clear Saved Plot Configus Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class ClearSavedPlotConfigs extends UnsecuredActionImpl<ClearSavedPlotConfigsResult>
{
    /** User id. */
    private String userID;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private ClearSavedPlotConfigs()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param userID
     *            user id.
     */
    public ClearSavedPlotConfigs(final String userID)
    {
        this.userID = userID;
    }

    /**
     * Get user id.
     * 
     * @return user id.
     */
    public final String getUserID()
    {
        return userID;
    }
}
