package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Clear Saved Plot Configs Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class ClearSavedPlotConfigsResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 7386753198513322707L;

    /**
     * Constructor.
     */
    public ClearSavedPlotConfigsResult()
    {
    }
}
