package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Clear Data Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class ClearDataResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -5797958596299894407L;

    /**
     * Constructor.
     */
    public ClearDataResult()
    {
    }
}
