package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Generate Client ID Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GenerateClientID extends UnsecuredActionImpl<GenerateClientIDResult>
{
    /**
     * Constructor.
     */
    public GenerateClientID()
    {
    }
}
