package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Channels Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetChannelsResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -7690517215034776788L;
    
    /** Channels set. */
    private List<String> channels;

    /**
     * Constructor (for serialization).
     */
    @SuppressWarnings("unused")
    private GetChannelsResult()
    {
        // For serialization only
    }

    /**
     * Constructor.
     * 
     * @param channels
     *            insertion-ordered set of channels.
     */
    public GetChannelsResult(final List<String> channels)
    {
        this.channels = channels;
    }

    /**
     * Get channels.
     * 
     * @return insertion-ordered set of channels.
     */
    public final List<String> getChannels()
    {
        return channels;
    }
}
