package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Types Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetCorrTypesResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 8460407294791603668L;
    
    /** Types. */
    private List<String> corrTypes;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetCorrTypesResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param corrTypes
     *            correction types.
     */
    public GetCorrTypesResult(final List<String> corrTypes)
    {
        this.corrTypes = corrTypes;
    }

    /**
     * Get correction types.
     * 
     * @return correction types.
     */
    public final List<String> getCorrTypes()
    {
        return corrTypes;
    }
}
