package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Get Types Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetCorrTypes extends UnsecuredActionImpl<GetCorrTypesResult>
{
    /** Catalog. */
    private String catalog;
    /** Source. */
    private String gprc;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetCorrTypes()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param catalog
     *            catalog.
     * @param gprc
     *            GPRC.
     */
    public GetCorrTypes(final String catalog, final String gprc)
    {
        this.catalog = catalog;
        this.gprc = gprc;
    }

    /**
     * Get catalog.
     * 
     * @return catalog.
     */
    public final String getCatalog()
    {
        return catalog;
    }

    /**
     * Get GPRC.
     * 
     * @return GRPC.
     */
    public final String getGPRC()
    {
        return gprc;
    }
}
