package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Get Dates Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetDateTimes extends UnsecuredActionImpl<GetDateTimesResult>
{
    /** Catalog. */
    private String catalog;
    /** Source. */
    private String gprc;
    /** Type. */
    private String corrType;
    /** Sat/Instr. */
    private String satInstr;
    /** Reference Sat/Instr. */
    private String refSatInstr;
    /** Mode. */
    private String mode;
    /** Year. */
    private String year;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetDateTimes()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param catalog
     *            catalog.
     * @param gprc
     *            GPRC.
     * @param corrType
     *            correction type.
     * @param satInstr
     *            sat/instr.
     * @param refSatInstr
     *            reference sat/instr.
     * @param mode
     *            mode.
     * @param year
     *            year.
     */
    public GetDateTimes(final String catalog, final String gprc, final String corrType, final String satInstr,
            final String refSatInstr, final String mode, final String year)
    {
        this.catalog = catalog;
        this.gprc = gprc;
        this.corrType = corrType;
        this.satInstr = satInstr;
        this.refSatInstr = refSatInstr;
        this.mode = mode;
        this.year = year;
    }

    /**
     * Get catalog.
     * 
     * @return catalog.
     */
    public final String getCatalog()
    {
        return catalog;
    }

    /**
     * Get GPRC.
     * 
     * @return gprc.
     */
    public final String getGPRC()
    {
        return gprc;
    }

    /**
     * Get correction type.
     * 
     * @return corrType.
     */
    public final String getCorrType()
    {
        return corrType;
    }

    /**
     * Get sat/instr.
     * 
     * @return sat/instr.
     */
    public final String getSatInstr()
    {
        return satInstr;
    }

    /**
     * Get reference sat/instr.
     * 
     * @return reference sat/instr.
     */
    public final String getRefSatInstr()
    {
        return refSatInstr;
    }

    /**
     * Get mode.
     * 
     * @return mode.
     */
    public final String getMode()
    {
        return mode;
    }
    
    /**
     * Get year.
     * 
     * @return year.
     */
    public final String getYear()
    {
        return year;
    }
}
