package org.eumetsat.usd.gcp.shared.action;

import java.util.Date;

import com.google.common.collect.Range;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Date Window Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetDateWindowResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 5399144426673849347L;
    
    /** Date window. */
    private Range<Date> dateWindow;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetDateWindowResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param dateWindow
     *            date window.
     */
    public GetDateWindowResult(final Range<Date> dateWindow)
    {
        this.dateWindow = dateWindow;
    }

    /**
     * Get date window.
     * 
     * @return date window.
     */
    public final Range<Date> getDateWindow()
    {
        return dateWindow;
    }
}
