package org.eumetsat.usd.gcp.shared.action;

import java.util.Map;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Datasets Names Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetDatasetsNamesResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -8638952687732630274L;
    
    /** Datasets names. */
    private Map<String, String> datasetsNames;

    /**
     * Constructor (for serialization only).
     */
    @SuppressWarnings("unused")
    private GetDatasetsNamesResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param datasetsNames
     *            datasets names.
     */
    public GetDatasetsNamesResult(final Map<String, String> datasetsNames)
    {
        this.datasetsNames = datasetsNames;
    }

    /**
     * Get datasets names.
     * 
     * @return datasets names.
     */
    public final Map<String, String> getDatasetsNames()
    {
        return datasetsNames;
    }
}
