package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Dates Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetDateTimesResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -1506118481084614664L;
    
    /** Date-times. */
    private List<String> dateTimes;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetDateTimesResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param dateTimes
     *            date-times.
     */
    public GetDateTimesResult(final List<String> dateTimes)
    {
        this.dateTimes = dateTimes;
    }

    /**
     * Get date-times.
     * 
     * @return chronologically ordered date-times.
     */
    public final List<String> getDateTimes()
    {
        return dateTimes;
    }
}
