package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Get GPRCs Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetGPRCs extends UnsecuredActionImpl<GetGPRCsResult>
{
    /** Catalog. */
    private String catalog;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetGPRCs()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param catalog
     *            catalog.
     */
    public GetGPRCs(final String catalog)
    {
        this.catalog = catalog;
    }

    /**
     * Get catalog.
     * 
     * @return catalog.
     */
    public final String getCatalog()
    {
        return catalog;
    }
}
