package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get GPRCs Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetGPRCsResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -2418439559074551678L;
    
    /** Sources. */
    private List<String> gprcs;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetGPRCsResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * @param gprcs GPRCs.
     */
    public GetGPRCsResult(final List<String> gprcs)
    {
        this.gprcs = gprcs;
    }

    /**
     * Get GPRCs.
     * @return GPRCs.
     */
    public final List<String> getGPRCs()
    {
        return gprcs;
    }
}
