package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import org.eumetsat.usd.gcp.shared.conf.HelpItem;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Help Items Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetHelpItemsResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -5117957654965622158L;

    /** Help items as configured. */
    private List<HelpItem> helpItems;

    @SuppressWarnings("unused")
    private GetHelpItemsResult()
    {
        // For serialization only
    }

    /**
     * Constructor.
     * 
     * @param helpItems
     *            help items in the configuration file.
     */
    public GetHelpItemsResult(List<HelpItem> helpItems)
    {
        this.helpItems = helpItems;
    }

    /**
     * Get help items.
     * 
     * @return help items in the configuration file.
     */
    public List<HelpItem> getHelpItems()
    {
        return helpItems;
    }
}
