package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Get Help Items. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetHelpItems extends UnsecuredActionImpl<GetHelpItemsResult>
{
    /**
     * Constructor.
     */
    public GetHelpItems()
    {
        
    }
}
