package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Get Implemented Catalogs Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetImplementedCatalogs extends UnsecuredActionImpl<GetImplementedCatalogsResult>
{
    /**
     * Constructor.
     */
    public GetImplementedCatalogs()
    {
    }
}
