package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Implemented Catalogs Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetImplementedCatalogsResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -7448687589213051218L;
    
    /** Catalog Names. */
    private List<String> catalogNames;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetImplementedCatalogsResult()
    {
        // For serialization only
    }

    /**
     * Constructor.
     * 
     * @param catalogNames
     *            catalog names.
     */
    public GetImplementedCatalogsResult(final List<String> catalogNames)
    {
        this.catalogNames = catalogNames;
    }

    /**
     * Get catalog names.
     * 
     * @return catalog names.
     */
    public final List<String> getCatalogNames()
    {
        return catalogNames;
    }
}
