package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Get Modes Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetModes extends UnsecuredActionImpl<GetModesResult>
{
    /** Catalog. */
    private String catalog;
    /** GPRC. */
    private String gprc;
    /** Correction Type. */
    private String corrType;
    /** Sat/intr. */
    private String satInstr;
    /** Reference sat/instr. */
    private String refSatInstr;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetModes()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param catalog
     *            catalog.
     * @param gprc
     *            GPRC.
     * @param corrType
     *            correction type.
     * @param satInstr
     *            sat/instr.
     * @param refSatInstr
     *            reference sat/instr.
     */
    public GetModes(final String catalog, final String gprc, final String corrType, final String satInstr,
            final String refSatInstr)
    {
        this.catalog = catalog;
        this.gprc = gprc;
        this.corrType = corrType;
        this.satInstr = satInstr;
        this.refSatInstr = refSatInstr;
    }

    /**
     * Get catalog.
     * 
     * @return catalog.
     */
    public final String getCatalog()
    {
        return catalog;
    }

    /**
     * Get GPRC.
     * 
     * @return GPRC.
     */
    public final String getGPRC()
    {
        return gprc;
    }

    /**
     * Get correction type.
     * 
     * @return correction type.
     */
    public final String getCorrType()
    {
        return corrType;
    }

    /**
     * Get sat/instr.
     * 
     * @return sat/instr.
     */
    public final String getSatInstr()
    {
        return satInstr;
    }

    /**
     * Get reference sat/instr.
     * 
     * @return reference sat/instr.
     */
    public final String getRefSatInstr()
    {
        return refSatInstr;
    }
}
