package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Modes Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetModesResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 4788471955320754387L;
    
    /** Modes. */
    private List<String> modes;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetModesResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param modes
     *            modes.
     */
    public GetModesResult(final List<String> modes)
    {
        this.modes = modes;
    }

    /**
     * Get modes.
     * 
     * @return modes.
     */
    public final List<String> getModes()
    {
        return modes;
    }
}
