package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Sat/Instrs. Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetSatInstrsResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -1874007192115094826L;
    
    /** Sat/instrs. */
    private List<String> satInstrs;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetSatInstrsResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param satInstrs
     *            sat/instrs.
     */
    public GetSatInstrsResult(final List<String> satInstrs)
    {
        this.satInstrs = satInstrs;
    }

    /**
     * Get Sat/instrs.
     * 
     * @return sat/instrs.
     */
    public final List<String> getSatInstrs()
    {
        return satInstrs;
    }
}
