package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Get Std Scene Tb Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetStdSceneTb extends UnsecuredActionImpl<GetStdSceneTbResult>
{
    /** Catalog. */
    private String catalog;
    /** GPRC. */
    private String gprc;
    /** Correction Type. */
    private String corrType;
    /** Mode. */
    private String mode;
    /** Sat/instr. */
    private String satInstr;
    /** Reference sat/instr. */
    private String refSatInstr;
    /** Year. */
    private String year;
    /** Date. */
    private String date;
    /** Version. */
    private String version;
    /** Channel. */
    private String channel;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetStdSceneTb()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param catalog
     *            catalog.
     * @param gprc
     *            GPRC.
     * @param corrType
     *            correction type.
     * @param satInstr
     *            sat/instr.
     * @param refSatInstr
     *            reference sat/instr.
     * @param mode
     *            mode.
     * @param year
     *            year.
     * @param date
     *            date.
     * @param version
     *            version.
     * @param channel
     *            channel.
     */
    public GetStdSceneTb(final String catalog, final String gprc, final String corrType, final String satInstr,
            final String refSatInstr, final String mode, final String year, final String date, final String version,
            final String channel)
    {
        this.catalog = catalog;
        this.gprc = gprc;
        this.corrType = corrType;
        this.satInstr = satInstr;
        this.refSatInstr = refSatInstr;
        this.mode = mode;
        this.year = year;
        this.date = date;
        this.version = version;
        this.channel = channel;
    }

    /**
     * Get catalog.
     * 
     * @return catalog.
     */
    public final String getCatalog()
    {
        return catalog;
    }

    /**
     * Get GPRC.
     * 
     * @return GPRC.
     */
    public final String getGPRC()
    {
        return gprc;
    }

    /**
     * Get correction type.
     * 
     * @return correction type.
     */
    public final String getCorrType()
    {
        return corrType;
    }

    /**
     * Get mode.
     * 
     * @return mode.
     */
    public final String getMode()
    {
        return mode;
    }

    /**
     * Get sat/instr.
     * 
     * @return sat/instr.
     */
    public final String getSatInstr()
    {
        return satInstr;
    }

    /**
     * Get reference sat/instr.
     * 
     * @return reference sat/instr.
     */
    public final String getRefSatInstr()
    {
        return refSatInstr;
    }

    /**
     * Get year.
     * 
     * @return year.
     */
    public final String getYear()
    {
        return year;
    }

    /**
     * Get date.
     * 
     * @return date.
     */
    public final String getDate()
    {
        return date;
    }

    /**
     * Get version.
     * 
     * @return version.
     */
    public final String getVersion()
    {
        return version;
    }

    /**
     * Get channel.
     * 
     * @return channel.
     */
    public final String getChannel()
    {
        return channel;
    }
}
