package org.eumetsat.usd.gcp.shared.action;

import java.util.List;
import java.util.Map;

import org.eumetsat.usd.gcp.shared.conf.PlotConfiguration;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Saved Plot Configs Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetSavedPlotConfigsResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 3340715301013687342L;

    /** Saved Plot Configurations. */
    private Map<String, List<PlotConfiguration>> savedPlotConfigs;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetSavedPlotConfigsResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param savedPlotConfigs
     *            saved plot configurations.
     */
    public GetSavedPlotConfigsResult(final Map<String, List<PlotConfiguration>> savedPlotConfigs)
    {
        this.savedPlotConfigs = savedPlotConfigs;
    }

    /**
     * Get saved plot configurations.
     * 
     * @return saved plot configurations.
     */
    public final Map<String, List<PlotConfiguration>> getSavedPlotConfigs()
    {
        return savedPlotConfigs;
    }
}
