package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get standard scene tb Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetStdSceneTbResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 3665403765661538560L;
    
    /** Standard scene brightness temperature. */
    private double stdSceneTb;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetStdSceneTbResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param stdSceneTb
     *            standard scene brightness temperature.
     */
    public GetStdSceneTbResult(final double stdSceneTb)
    {
        this.stdSceneTb = stdSceneTb;
    }

    /**
     * Get standard brightness temperature.
     * 
     * @return standard brightness temperature.
     */
    public final double getStdSceneTb()
    {
        return stdSceneTb;
    }
}
