package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Get User Logged in Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetUserLoggedIn extends UnsecuredActionImpl<GetUserLoggedInResult>
{
    /**
     * Constructor.
     */
    public GetUserLoggedIn()
    {
    }
}
