package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Versions Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetVersionsResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -2132946314884163951L;
    
    /** Versions. */
    private List<String> versions;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetVersionsResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param versions
     *            versions.
     */
    public GetVersionsResult(final List<String> versions)
    {
        this.versions = versions;
    }

    /**
     * Get versions.
     * 
     * @return versions.
     */
    public final List<String> getVersions()
    {
        return versions;
    }
}
