package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Get Years Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class GetYearsResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 2642909109052711223L;
    
    /** Years. */
    private List<String> years;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private GetYearsResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param years
     *            years.
     */
    public GetYearsResult(final List<String> years)
    {
        this.years = years;
    }

    /**
     * Get years.
     * 
     * @return years.
     */
    public final List<String> getYears()
    {
        return years;
    }
}
