package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Login Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class Login extends UnsecuredActionImpl<LoginResult>
{
    /** Username. */
    private String username;
    /** Password. */
    private String password;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private Login()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param username
     *            username.
     * @param password
     *            password.
     */
    public Login(final String username, final String password)
    {
        this.username = username;
        this.password = password;
    }

    /**
     * Get username.
     * 
     * @return username.
     */
    public final String getUsername()
    {
        return username;
    }

    /**
     * Get password.
     * 
     * @return password.
     */
    public final String getPassword()
    {
        return password;
    }
}
