package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Logout Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class Logout extends UnsecuredActionImpl<LogoutResult>
{
    /**
     * Constructor.
     */
    public Logout()
    {
        
    }
}
