package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Logout Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class LogoutResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 8396474021906301359L;

    /**
     * Constructor.
     */
    public LogoutResult()
    {
    }
}
