package org.eumetsat.usd.gcp.shared.action;

import java.util.List;

import org.eumetsat.usd.gcp.shared.conf.PlotConfiguration;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Prepare Multiple Data Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class PrepareMultipleData extends UnsecuredActionImpl<PrepareMultipleDataResult>
{
    /** User id. */
    private String userID;
    /** Plot configurations. */
    private List<PlotConfiguration> plotConfigurations;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private PrepareMultipleData()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param userID
     *            user id.
     * @param plotConfigurations
     *            plot configurations.
     */
    public PrepareMultipleData(final String userID, final List<PlotConfiguration> plotConfigurations)
    {
        this.userID = userID;
        this.plotConfigurations = plotConfigurations;
    }

    /**
     * Get user id.
     * 
     * @return user id.
     */
    public final String getUserID()
    {
        return userID;
    }

    /**
     * Get plot configurations.
     * 
     * @return plot configurations.
     */
    public final List<PlotConfiguration> getPlotConfigurations()
    {
        return plotConfigurations;
    }
}
