package org.eumetsat.usd.gcp.shared.action;

import java.util.List;
import java.util.Map;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Prepare Multiple Data Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class PrepareMultipleDataResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 6602676605251611392L;
    
    /** User ID. */
    private String userID;
    
    /** Datasets names. */
    private List<String> datasetsNames;
    
    /** Download links. */
    private Map<String, String> downloadLinks;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private PrepareMultipleDataResult()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param userID
     *            user ID.
     * @param datasetsNames
     *            datasets names.
     * @param downloadLinks
     *            download links.
     */
    public PrepareMultipleDataResult(final String userID, final List<String> datasetsNames,
            final Map<String, String> downloadLinks)
    {
        this.userID = userID;
        this.datasetsNames = datasetsNames;
        this.downloadLinks = downloadLinks;
    }

    /**
     * Get user ID.
     * 
     * @return user ID.
     */
    public final String getUserID()
    {
        return userID;
    }

    /**
     * Get datasets names.
     * 
     * @return datasets names.
     */
    public final List<String> getDatasetsNames()
    {
        return datasetsNames;
    }

    /**
     * Get download links.
     * 
     * @return download links.
     */
    public final Map<String, String> getDownloadLinks()
    {
        return downloadLinks;
    }
}
