package org.eumetsat.usd.gcp.shared.action;

import org.eumetsat.usd.gcp.shared.conf.PlotConfiguration;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Prepare Data Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class PrepareData extends UnsecuredActionImpl<PrepareDataResult>
{
    /** User ID. */
    private String userID;
    /** Plot Configuration. */
    private PlotConfiguration plotConfiguration;
    /** Dataset URL. */
    private String datasetUrl;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private PrepareData()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param userID
     *            user ID.
     * @param plotConfiguration
     *            plot configuration.
     */
    public PrepareData(final String userID, final PlotConfiguration plotConfiguration)
    {
        this.userID = userID;
        this.plotConfiguration = plotConfiguration;
    }

    /**
     * Get user ID.
     * 
     * @return user ID.
     */
    public final String getUserID()
    {
        return userID;
    }

    /**
     * Get plot configuration.
     * 
     * @return plot configuration.
     */
    public final PlotConfiguration getPlotConfiguration()
    {
        return plotConfiguration;
    }

    /**
     * Get dataset URL.
     * 
     * @return dataset URL.
     */
    public final String getDatasetUrl()
    {
        return datasetUrl;
    }
}
