package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Register Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class Register extends UnsecuredActionImpl<RegisterResult>
{
    /** Username. */
    private String username;
    /** Password. */
    private String password;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private Register()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param username
     *            username.
     * @param password
     *            password.
     */
    public Register(final String username, final String password)
    {
        this.username = username;
        this.password = password;
    }

    /**
     * Get username.
     * 
     * @return username.
     */
    public final String getUsername()
    {
        return username;
    }

    /**
     * Get password.
     * 
     * @return password.
     */
    public final String getPassword()
    {
        return password;
    }
}
