package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Remove Saved Plot Config Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class RemoveSavedPlotConfig extends UnsecuredActionImpl<RemoveSavedPlotConfigResult>
{
    /** User ID. */
    private String userID;
    /** Plot Config Name. */
    private String plotConfigName;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private RemoveSavedPlotConfig()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param userID
     *            user id.
     * @param plotConfigName
     *            plot configuration name.
     */
    public RemoveSavedPlotConfig(final String userID, final String plotConfigName)
    {
        this.userID = userID;
        this.plotConfigName = plotConfigName;
    }

    /**
     * Get user id.
     * 
     * @return user id.
     */
    public final String getUserID()
    {
        return userID;
    }

    /**
     * Get plot configuration name.
     * 
     * @return plot configuration name.
     */
    public final String getPlotConfigName()
    {
        return plotConfigName;
    }
}
