package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Remove Saved Plot Config Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class RemoveSavedPlotConfigResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = -2473325260773278962L;

    /**
     * Constructor.
     */
    public RemoveSavedPlotConfigResult()
    {
    }
}
