package org.eumetsat.usd.gcp.shared.action;

import com.gwtplatform.dispatch.rpc.shared.Result;

/**
 * Save Plot Configuration Action Result. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class SavePlotConfigResult implements Result
{
    /** Auto-generated serial version UID. */
    private static final long serialVersionUID = 7975231751262857313L;

    /**
     * Constructor.
     */
    public SavePlotConfigResult()
    {
    }
}
