package org.eumetsat.usd.gcp.shared.action;

import java.util.ArrayList;

import org.eumetsat.usd.gcp.shared.conf.PlotConfiguration;

import com.gwtplatform.dispatch.rpc.shared.UnsecuredActionImpl;

/**
 * Save Plot Configuration Action Input. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class SavePlotConfig extends UnsecuredActionImpl<SavePlotConfigResult>
{
    /** User id. */
    private String userID;
    /** Plot configurations. */
    private ArrayList<PlotConfiguration> plotConfigs;

    /**
     * Constructor (for serialisation only).
     */
    @SuppressWarnings("unused")
    private SavePlotConfig()
    {
        // For serialisation only
    }

    /**
     * Constructor.
     * 
     * @param userID
     *            user id.
     * @param plotConfigs
     *            plot configurations.
     */
    public SavePlotConfig(final String userID, final ArrayList<PlotConfiguration> plotConfigs)
    {
        this.userID = userID;
        this.plotConfigs = plotConfigs;
    }

    /**
     * Get user id.
     * 
     * @return user id.
     */
    public final String getUserID()
    {
        return userID;
    }

    /**
     * Get plot configurations.
     * 
     * @return plot configurations.
     */
    public final ArrayList<PlotConfiguration> getPlotConfigs()
    {
        return plotConfigs;
    }
}
