//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.30 at 10:36:23 AM CEST 
//


package org.eumetsat.usd.gcp.server.conf.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="catalogs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="catalog" type="{}CatalogType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="global_attributes_names">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rad_to_tb_conv_formula" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tb_to_rad_conv_formula" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="c1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="c2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="global_attributes_defaults">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rad_to_tb_conv_formula" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tb_to_rad_conv_formula" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="c1" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="c2" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="variables_names">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="radiance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="channel_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="offset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="offset_se" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="slope" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="slope_se" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="covariance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="std_scene_tb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="alpha" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="beta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wnc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="help_items">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="help_item" type="{}HelpItemType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "catalogs",
    "globalAttributesNames",
    "globalAttributesDefaults",
    "variablesNames",
    "helpItems"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(required = true)
    protected Configuration.Catalogs catalogs;
    @XmlElement(name = "global_attributes_names", required = true)
    protected Configuration.GlobalAttributesNames globalAttributesNames;
    @XmlElement(name = "global_attributes_defaults", required = true)
    protected Configuration.GlobalAttributesDefaults globalAttributesDefaults;
    @XmlElement(name = "variables_names", required = true)
    protected Configuration.VariablesNames variablesNames;
    @XmlElement(name = "help_items", required = true)
    protected Configuration.HelpItems helpItems;

    /**
     * Gets the value of the catalogs property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Catalogs }
     *     
     */
    public Configuration.Catalogs getCatalogs() {
        return catalogs;
    }

    /**
     * Sets the value of the catalogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Catalogs }
     *     
     */
    public void setCatalogs(Configuration.Catalogs value) {
        this.catalogs = value;
    }

    /**
     * Gets the value of the globalAttributesNames property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.GlobalAttributesNames }
     *     
     */
    public Configuration.GlobalAttributesNames getGlobalAttributesNames() {
        return globalAttributesNames;
    }

    /**
     * Sets the value of the globalAttributesNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.GlobalAttributesNames }
     *     
     */
    public void setGlobalAttributesNames(Configuration.GlobalAttributesNames value) {
        this.globalAttributesNames = value;
    }

    /**
     * Gets the value of the globalAttributesDefaults property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.GlobalAttributesDefaults }
     *     
     */
    public Configuration.GlobalAttributesDefaults getGlobalAttributesDefaults() {
        return globalAttributesDefaults;
    }

    /**
     * Sets the value of the globalAttributesDefaults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.GlobalAttributesDefaults }
     *     
     */
    public void setGlobalAttributesDefaults(Configuration.GlobalAttributesDefaults value) {
        this.globalAttributesDefaults = value;
    }

    /**
     * Gets the value of the variablesNames property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.VariablesNames }
     *     
     */
    public Configuration.VariablesNames getVariablesNames() {
        return variablesNames;
    }

    /**
     * Sets the value of the variablesNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.VariablesNames }
     *     
     */
    public void setVariablesNames(Configuration.VariablesNames value) {
        this.variablesNames = value;
    }

    /**
     * Gets the value of the helpItems property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.HelpItems }
     *     
     */
    public Configuration.HelpItems getHelpItems() {
        return helpItems;
    }

    /**
     * Sets the value of the helpItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.HelpItems }
     *     
     */
    public void setHelpItems(Configuration.HelpItems value) {
        this.helpItems = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="catalog" type="{}CatalogType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "catalog"
    })
    public static class Catalogs {

        @XmlElement(required = true)
        protected List<CatalogType> catalog;

        /**
         * Gets the value of the catalog property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the catalog property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCatalog().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CatalogType }
         * 
         * 
         */
        public List<CatalogType> getCatalog() {
            if (catalog == null) {
                catalog = new ArrayList<CatalogType>();
            }
            return this.catalog;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rad_to_tb_conv_formula" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tb_to_rad_conv_formula" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="c1" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="c2" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "radToTbConvFormula",
        "tbToRadConvFormula",
        "c1",
        "c2"
    })
    public static class GlobalAttributesDefaults {

        @XmlElement(name = "rad_to_tb_conv_formula", required = true)
        protected String radToTbConvFormula;
        @XmlElement(name = "tb_to_rad_conv_formula", required = true)
        protected String tbToRadConvFormula;
        protected double c1;
        protected double c2;

        /**
         * Gets the value of the radToTbConvFormula property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRadToTbConvFormula() {
            return radToTbConvFormula;
        }

        /**
         * Sets the value of the radToTbConvFormula property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRadToTbConvFormula(String value) {
            this.radToTbConvFormula = value;
        }

        /**
         * Gets the value of the tbToRadConvFormula property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTbToRadConvFormula() {
            return tbToRadConvFormula;
        }

        /**
         * Sets the value of the tbToRadConvFormula property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTbToRadConvFormula(String value) {
            this.tbToRadConvFormula = value;
        }

        /**
         * Gets the value of the c1 property.
         * 
         */
        public double getC1() {
            return c1;
        }

        /**
         * Sets the value of the c1 property.
         * 
         */
        public void setC1(double value) {
            this.c1 = value;
        }

        /**
         * Gets the value of the c2 property.
         * 
         */
        public double getC2() {
            return c2;
        }

        /**
         * Sets the value of the c2 property.
         * 
         */
        public void setC2(double value) {
            this.c2 = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="rad_to_tb_conv_formula" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tb_to_rad_conv_formula" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="c1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="c2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filename",
        "radToTbConvFormula",
        "tbToRadConvFormula",
        "c1",
        "c2"
    })
    public static class GlobalAttributesNames {

        @XmlElement(required = true)
        protected String filename;
        @XmlElement(name = "rad_to_tb_conv_formula", required = true)
        protected String radToTbConvFormula;
        @XmlElement(name = "tb_to_rad_conv_formula", required = true)
        protected String tbToRadConvFormula;
        @XmlElement(required = true)
        protected String c1;
        @XmlElement(required = true)
        protected String c2;

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilename() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilename(String value) {
            this.filename = value;
        }

        /**
         * Gets the value of the radToTbConvFormula property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRadToTbConvFormula() {
            return radToTbConvFormula;
        }

        /**
         * Sets the value of the radToTbConvFormula property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRadToTbConvFormula(String value) {
            this.radToTbConvFormula = value;
        }

        /**
         * Gets the value of the tbToRadConvFormula property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTbToRadConvFormula() {
            return tbToRadConvFormula;
        }

        /**
         * Sets the value of the tbToRadConvFormula property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTbToRadConvFormula(String value) {
            this.tbToRadConvFormula = value;
        }

        /**
         * Gets the value of the c1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getC1() {
            return c1;
        }

        /**
         * Sets the value of the c1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setC1(String value) {
            this.c1 = value;
        }

        /**
         * Gets the value of the c2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getC2() {
            return c2;
        }

        /**
         * Sets the value of the c2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setC2(String value) {
            this.c2 = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="help_item" type="{}HelpItemType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "helpItem"
    })
    public static class HelpItems {

        @XmlElement(name = "help_item")
        protected List<HelpItemType> helpItem;

        /**
         * Gets the value of the helpItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the helpItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHelpItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HelpItemType }
         * 
         * 
         */
        public List<HelpItemType> getHelpItem() {
            if (helpItem == null) {
                helpItem = new ArrayList<HelpItemType>();
            }
            return this.helpItem;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tb" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="radiance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="channel_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="offset" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="offset_se" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="slope" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="slope_se" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="covariance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="std_scene_tb" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="alpha" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="beta" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wnc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date",
        "tb",
        "radiance",
        "channelName",
        "offset",
        "offsetSe",
        "slope",
        "slopeSe",
        "covariance",
        "stdSceneTb",
        "alpha",
        "beta",
        "wnc"
    })
    public static class VariablesNames {

        @XmlElement(required = true)
        protected String date;
        @XmlElement(required = true)
        protected String tb;
        @XmlElement(required = true)
        protected String radiance;
        @XmlElement(name = "channel_name", required = true)
        protected String channelName;
        @XmlElement(required = true)
        protected String offset;
        @XmlElement(name = "offset_se", required = true)
        protected String offsetSe;
        @XmlElement(required = true)
        protected String slope;
        @XmlElement(name = "slope_se", required = true)
        protected String slopeSe;
        @XmlElement(required = true)
        protected String covariance;
        @XmlElement(name = "std_scene_tb", required = true)
        protected String stdSceneTb;
        @XmlElement(required = true)
        protected String alpha;
        @XmlElement(required = true)
        protected String beta;
        @XmlElement(required = true)
        protected String wnc;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the tb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTb() {
            return tb;
        }

        /**
         * Sets the value of the tb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTb(String value) {
            this.tb = value;
        }

        /**
         * Gets the value of the radiance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRadiance() {
            return radiance;
        }

        /**
         * Sets the value of the radiance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRadiance(String value) {
            this.radiance = value;
        }

        /**
         * Gets the value of the channelName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChannelName() {
            return channelName;
        }

        /**
         * Sets the value of the channelName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChannelName(String value) {
            this.channelName = value;
        }

        /**
         * Gets the value of the offset property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOffset() {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOffset(String value) {
            this.offset = value;
        }

        /**
         * Gets the value of the offsetSe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOffsetSe() {
            return offsetSe;
        }

        /**
         * Sets the value of the offsetSe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOffsetSe(String value) {
            this.offsetSe = value;
        }

        /**
         * Gets the value of the slope property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSlope() {
            return slope;
        }

        /**
         * Sets the value of the slope property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSlope(String value) {
            this.slope = value;
        }

        /**
         * Gets the value of the slopeSe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSlopeSe() {
            return slopeSe;
        }

        /**
         * Sets the value of the slopeSe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSlopeSe(String value) {
            this.slopeSe = value;
        }

        /**
         * Gets the value of the covariance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCovariance() {
            return covariance;
        }

        /**
         * Sets the value of the covariance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCovariance(String value) {
            this.covariance = value;
        }

        /**
         * Gets the value of the stdSceneTb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStdSceneTb() {
            return stdSceneTb;
        }

        /**
         * Sets the value of the stdSceneTb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStdSceneTb(String value) {
            this.stdSceneTb = value;
        }

        /**
         * Gets the value of the alpha property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlpha() {
            return alpha;
        }

        /**
         * Sets the value of the alpha property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlpha(String value) {
            this.alpha = value;
        }

        /**
         * Gets the value of the beta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeta() {
            return beta;
        }

        /**
         * Sets the value of the beta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeta(String value) {
            this.beta = value;
        }

        /**
         * Gets the value of the wnc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWnc() {
            return wnc;
        }

        /**
         * Sets the value of the wnc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWnc(String value) {
            this.wnc = value;
        }

    }

}
