//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.30 at 10:36:23 AM CEST 
//


package org.eumetsat.usd.gcp.server.conf.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.eumetsat.usd.gcp.server.conf.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.eumetsat.usd.gcp.server.conf.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Configuration.GlobalAttributesDefaults }
     * 
     */
    public Configuration.GlobalAttributesDefaults createConfigurationGlobalAttributesDefaults() {
        return new Configuration.GlobalAttributesDefaults();
    }

    /**
     * Create an instance of {@link Configuration.Catalogs }
     * 
     */
    public Configuration.Catalogs createConfigurationCatalogs() {
        return new Configuration.Catalogs();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link CatalogType }
     * 
     */
    public CatalogType createCatalogType() {
        return new CatalogType();
    }

    /**
     * Create an instance of {@link Configuration.VariablesNames }
     * 
     */
    public Configuration.VariablesNames createConfigurationVariablesNames() {
        return new Configuration.VariablesNames();
    }

    /**
     * Create an instance of {@link Configuration.GlobalAttributesNames }
     * 
     */
    public Configuration.GlobalAttributesNames createConfigurationGlobalAttributesNames() {
        return new Configuration.GlobalAttributesNames();
    }

    /**
     * Create an instance of {@link HelpItemType }
     * 
     */
    public HelpItemType createHelpItemType() {
        return new HelpItemType();
    }

    /**
     * Create an instance of {@link Configuration.HelpItems }
     * 
     */
    public Configuration.HelpItems createConfigurationHelpItems() {
        return new Configuration.HelpItems();
    }

}
