package org.eumetsat.usd.gcp.server.guice;

import org.eumetsat.usd.gcp.server.action.ClearDataActionHandler;
import org.eumetsat.usd.gcp.server.action.ClearSavedPlotConfigsActionHandler;
import org.eumetsat.usd.gcp.server.action.GenerateUserIDActionHandler;
import org.eumetsat.usd.gcp.server.action.GetChannelsActionHandler;
import org.eumetsat.usd.gcp.server.action.GetDatasetsNamesActionHandler;
import org.eumetsat.usd.gcp.server.action.GetDateWindowActionHandler;
import org.eumetsat.usd.gcp.server.action.GetDateTimesActionHandler;
import org.eumetsat.usd.gcp.server.action.GetHelpItemsActionHandler;
import org.eumetsat.usd.gcp.server.action.GetImplementedCatalogsActionHandler;
import org.eumetsat.usd.gcp.server.action.GetModesActionHandler;
import org.eumetsat.usd.gcp.server.action.GetRefSatInstrsActionHandler;
import org.eumetsat.usd.gcp.server.action.GetSatInstrsActionHandler;
import org.eumetsat.usd.gcp.server.action.GetSavedPlotConfigsActionHandler;
import org.eumetsat.usd.gcp.server.action.GetGPRCsActionHandler;
import org.eumetsat.usd.gcp.server.action.GetStdSceneTbActionHandler;
import org.eumetsat.usd.gcp.server.action.GetCorrTypesActionHandler;
import org.eumetsat.usd.gcp.server.action.GetUserLoggedInActionHandler;
import org.eumetsat.usd.gcp.server.action.GetVersionsActionHandler;
import org.eumetsat.usd.gcp.server.action.GetYearsActionHandler;
import org.eumetsat.usd.gcp.server.action.LoggedInActionValidator;
import org.eumetsat.usd.gcp.server.action.LoginActionHandler;
import org.eumetsat.usd.gcp.server.action.LogoutActionHandler;
import org.eumetsat.usd.gcp.server.action.PrepareDataActionHandler;
import org.eumetsat.usd.gcp.server.action.PrepareMultipleDataActionHandler;
import org.eumetsat.usd.gcp.server.action.RegisterActionHandler;
import org.eumetsat.usd.gcp.server.action.RemoveSavedPlotConfigActionHandler;
import org.eumetsat.usd.gcp.server.action.SavePlotConfigActionHandler;
import org.eumetsat.usd.gcp.shared.action.ClearData;
import org.eumetsat.usd.gcp.shared.action.ClearSavedPlotConfigs;
import org.eumetsat.usd.gcp.shared.action.GenerateClientID;
import org.eumetsat.usd.gcp.shared.action.GetChannels;
import org.eumetsat.usd.gcp.shared.action.GetDatasetsNames;
import org.eumetsat.usd.gcp.shared.action.GetDateWindow;
import org.eumetsat.usd.gcp.shared.action.GetDateTimes;
import org.eumetsat.usd.gcp.shared.action.GetHelpItems;
import org.eumetsat.usd.gcp.shared.action.GetImplementedCatalogs;
import org.eumetsat.usd.gcp.shared.action.GetModes;
import org.eumetsat.usd.gcp.shared.action.GetRefSatInstrs;
import org.eumetsat.usd.gcp.shared.action.GetSatInstrs;
import org.eumetsat.usd.gcp.shared.action.GetSavedPlotConfigs;
import org.eumetsat.usd.gcp.shared.action.GetGPRCs;
import org.eumetsat.usd.gcp.shared.action.GetStdSceneTb;
import org.eumetsat.usd.gcp.shared.action.GetCorrTypes;
import org.eumetsat.usd.gcp.shared.action.GetUserLoggedIn;
import org.eumetsat.usd.gcp.shared.action.GetVersions;
import org.eumetsat.usd.gcp.shared.action.GetYears;
import org.eumetsat.usd.gcp.shared.action.Login;
import org.eumetsat.usd.gcp.shared.action.Logout;
import org.eumetsat.usd.gcp.shared.action.PrepareData;
import org.eumetsat.usd.gcp.shared.action.PrepareMultipleData;
import org.eumetsat.usd.gcp.shared.action.Register;
import org.eumetsat.usd.gcp.shared.action.RemoveSavedPlotConfig;
import org.eumetsat.usd.gcp.shared.action.SavePlotConfig;

import com.gwtplatform.dispatch.rpc.server.guice.HandlerModule;

/**
 * Server Module. Generated by GWTP Plugin.
 * 
 * @author USD/C/PBe
 */
public class ServerModule extends HandlerModule
{
    @Override
    protected final void configureHandlers()
    {
        bindHandler(GetImplementedCatalogs.class, GetImplementedCatalogsActionHandler.class);

        bindHandler(GetGPRCs.class, GetGPRCsActionHandler.class);

        bindHandler(GetCorrTypes.class, GetCorrTypesActionHandler.class);

        bindHandler(GetSatInstrs.class, GetSatInstrsActionHandler.class);

        bindHandler(GetRefSatInstrs.class, GetRefSatInstrsActionHandler.class);

        bindHandler(GetModes.class, GetModesActionHandler.class);

        bindHandler(GetYears.class, GetYearsActionHandler.class);

        bindHandler(GetDateTimes.class, GetDateTimesActionHandler.class);

        bindHandler(GetVersions.class, GetVersionsActionHandler.class);

        bindHandler(GetChannels.class, GetChannelsActionHandler.class);

        bindHandler(GetStdSceneTb.class, GetStdSceneTbActionHandler.class);

        bindHandler(PrepareData.class, PrepareDataActionHandler.class);

        bindHandler(GetDatasetsNames.class, GetDatasetsNamesActionHandler.class);

        bindHandler(GenerateClientID.class, GenerateUserIDActionHandler.class);

        bindHandler(ClearData.class, ClearDataActionHandler.class);

        bindHandler(GetDateWindow.class, GetDateWindowActionHandler.class);

        bindHandler(ClearSavedPlotConfigs.class,
                ClearSavedPlotConfigsActionHandler.class,
                LoggedInActionValidator.class);

        bindHandler(SavePlotConfig.class, SavePlotConfigActionHandler.class, LoggedInActionValidator.class);

        bindHandler(GetSavedPlotConfigs.class, GetSavedPlotConfigsActionHandler.class, LoggedInActionValidator.class);

        bindHandler(Login.class, LoginActionHandler.class);

        bindHandler(Logout.class, LogoutActionHandler.class, LoggedInActionValidator.class);

        bindHandler(GetUserLoggedIn.class, GetUserLoggedInActionHandler.class);

        bindHandler(Register.class, RegisterActionHandler.class);

        bindHandler(RemoveSavedPlotConfig.class, RemoveSavedPlotConfigActionHandler.class);

        bindHandler(PrepareMultipleData.class, PrepareMultipleDataActionHandler.class);

        bindHandler(GetHelpItems.class, GetHelpItemsActionHandler.class);
    }
}
